/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable.PrintMode;
   
    private void FieldNama(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private static class tbl_bahanbangunanbeton {

        private static Object getValueAt(int baris, int i) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public tbl_bahanbangunanbeton() {
        }
    }
/**
 *
 * @author ajeng
 */
public class bahanbangunanbeton extends javax.swing.JFrame {

    private Object load_table;
        private String nama;
        private Object jenismaterial;

    /**
     * Creates new form Bahanbangunanbeton
     */
    public bahanbangunanbeton() {
        initComponents();
        this.bahanbangunanbeton(); 
    }

    private DefaultTableModel tbl_bahanbangunanbeton;
    private String SQL;
    
    public void TampilData() {
        tbl_bahanbangunanbeton = new DefaultTableModel();
        tbl_bahanbangunanbeton.addColumn("Nama");
        tbl_bahanbangunanbeton.addColumn("Berat Jenis");
        tbl_bahanbangunanbeton.addColumn("Presentase");
        tbl_bahanbangunanbeton.addColumn("Jenis Material");
        load_table.setModel(tbl_bahanbangunanbeton);
        Connection conn = Config.getConnection();
        try {
            java.sql.Statement stmt
                    = conn.createStatement();
            SQL = "select * from bahanbangunanbeton";
            java.sql.ResultSet res
                    = stmt.executeQuery(SQL);
            while (res.next()) {
                tbl_bahanbangunanbeton.addRow(new Object[]{
                    res.getString("nama"),
                    res.getString("berat_jenis"),
                    res.getString("persentase"),
                    res.getString("jenis_material"),
         
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FieldNama = new javax.swing.JTextField();
        FieldBeratjenis = new javax.swing.JTextField();
        FieldPresentase = new javax.swing.JTextField();
        ComboMaterial = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        load_tabel = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bahan Beton");

        jLabel2.setText("Nama");

        jLabel3.setText("Berat Jenis");

        jLabel4.setText("Presentase");

        jLabel5.setText("Jenis Material");

        FieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNamaActionPerformed(evt);
            }
        });

        ComboMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Besi ", "Agregat Halus", "Agregat Kasar", "Semen", "Air" }));

        jButton1.setText("Tambah Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        load_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Berat Jenis", "Presentase", "Jenis Material"
            }
        ));
        load_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                load_tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(load_tabel);

        jButton3.setText("Hapus Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Cetak Data");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FieldBeratjenis, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldPresentase, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboMaterial, javax.swing.GroupLayout.Alignment.LEADING, 0, 225, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldBeratjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldPresentase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // Validasi input data
            String nama = FieldNama.getText();
            String beratjenis = FieldBeratjenis.getText();
            String presentase = TextPresentase.getText();
            String jenismaterial = ComboMaterial.getSelectedItem().toString();

            if (nama.isEmpty() || beratjenis.isEmpty() || presentase.isEmpty() || jenismaterial.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Pastikan na adalah angka jika tipe data di database adalah integer
            try {
                Integer.parseInt(nama);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Nama harus sesuai", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Pastikan nilai berat jenis tidak melebihi batas yang diperbolehkan
            if (beratjenis()>15) {
                JOptionPane.showMessageDialog(this, "Berat jenis", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Connection conn = Config.getConnection();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Failed to connect to the database.", "Database Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            PreparedStatement stmt = conn.prepareStatement("INSERT INTO Bahanbanguanabeton(nama, beratjenis, presentase, jenismaterial) VALUES (?, ?, ?, ?, ?)");
            stmt.setString(1, nama);
            stmt.setString(2, beratjenis);
            stmt.setString(3, presentase);
            stmt.setString(4, jenismaterial);

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("SQL Exception: " + e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 Connection conn = Config.getConnection();
        int confirm
                = JOptionPane.showConfirmDialog(null, "Apakah anda yakiningin menghapus data tersebut?", "Konfirmasi",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );
        if (confirm == 0) {
            try {
                java.sql.PreparedStatement stmt
                        = conn.prepareStatement("delete from bahanbangunanbeton where nama='" + FieldNama.getText() + "'  ");

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null,
                        "Data berhasil dihapus", "Pesan",
                        JOptionPane.INFORMATION_MESSAGE);
                TampilData();
                FieldNama.setText("");
                FieldBeratjenis.setText("");
                TextPresentase.setText("");
                ComboMaterial.setSelectedItem("");        
                FieldNama.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,
                        "Data gagal di hapus" + e.getMessage(), "Pesan",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
try {
            Connection conn = Config.getConnection();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Failed to connect to the database.", "Database Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String nama = FieldNama.getText();
            String beratjenis = FieldBeratjenis.getText();
            String presentase = FieldPresentase.getText();
            String jenismaterial = ComboMaterial.getSelectedItem().toString();

            // Validasi input data
            if (nama.isEmpty() || beratjenis.isEmpty() || presentase.isEmpty() || jenismaterial.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Pastikan berat jenis adalah angka jika tipe data di database adalah integer
            try {
                Integer.parseInt(beratjenis);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "beratjenis harus berupa angka", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Pastikan Presentase adalah angka jika tipe data di database adalah integer
            try {
                Integer.parseInt(presentase);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Presentase harus berupa angka", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            PreparedStatement stmt = conn.prepareStatement(
                    "UPDATE Bahan_bangunan_beton SET nama = ?, beratjenis = ?, presentase = ?, jenismaterial = ?, WHERE nama = ?"
            );
            stmt.setString(1, nama);
            stmt.setString(2, beratjenis);
            stmt.setString(3, presentase);
            stmt.setString(4, jenismaterial);
            stmt.setString(6, nama); 
            // Set parameter keenam untuk where clause
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("SQL Exception: " + e.getMessage());
            e.printStackTrace();
        }                                  

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       load_table.print(PrintMode.FIT_WIDTH, new MessageFormat("BAHAN BANGUNAN BETON"), null);
}
        catch(PrinterException ex){
        Logger.getLogger(bahanbangunanbeton.class.getName()).log(Level.SEVERE, null, ex);
       }
        private int beratjenis() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }                                     

        private bahanbangunanbeton() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }           

       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void load_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_load_tabelMouseClicked
        // TODO add your handling code here:
int baris = load_table.getSelectedRow();
        FieldNama(tbl_bahanbangunanbeton.getValueAt(baris,0).toString());  
        FieldBeratjenis.setText(tbl_bahanbangunanbeton.getValueAt(baris,1).toString());
        FieldPresentase.setText(tbl_bahanbangunanbeton.getValueAt(baris,2).toString());
        ComboMaterial.setSelectedItem(tbl_bahanbangunanbeton.getValueAt(baris, 3).toString()
        );                                   
    }//GEN-LAST:event_load_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bahanbangunanbeton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bahanbangunanbeton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bahanbangunanbeton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bahanbangunanbeton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bahanbangunanbeton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboMaterial;
    private javax.swing.JTextField FieldBeratjenis;
    private javax.swing.JTextField FieldNama;
    private javax.swing.JTextField FieldPresentase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable load_tabel;
    // End of variables declaration//GEN-END:variables

